/*
 * SPI1_config.h
 *
 *  Created on: Sep 28, 2020
 *      Author: noureldeen albrmky
 */

#ifndef SPI1_CONFIG_H_
#define SPI1_CONFIG_H_

//SPI 	//I2S
#define PERIPHERALS_AS_ 				SPI

//SLAVE_MODE	//MASTER_MODE
#define SPI_WORK_IN 					MASTER_MODE

//DATA_FRAME_8	DATA_FRAME_16
#define DATA_FRAME_FORMAT				DATA_FRAME_8

//MSB	LSB
#define FIRST_BIT_OUT					MSB

//CLK_2		//CLK_4		//CLK_8		//CLK_16
//CLK_32	//CLK_64	//CLK_128	//CLK_256
#define SPI_BAUD_RATE					CLK_2

//IDEAL_LOW		IDEAL_HIGH
#define CLOCK_POLARITY 					IDEAL_HIGH

//CAPTURE_WITH_LEADING_EDGE		CAPTURE_WITH_TRAILING_EDGE
#define CLOCK_PHASE						CAPTURE_WITH_TRAILING_EDGE

//HARDWARE_EXTERNALLY 	//SOFTWARE_INTERNALLY
#define NSS_CONTROL						SOFTWARE_INTERNALLY

//UNIDIRECTIONAL_FULL_DUPLEX	all pins are used
//UNIDIRECTIONAL_RECEIVE_ONLY	if master MISO Free & if slave MOSI free
//BIDIRECTIONAL_RECEIVE_ONLY	ONLY MOSI in master and MISO in slave are used
//BIDIRECTIONAL_TRANSMIT_ONLY	ONLY MOSI in master and MISO in slave are used
#define SPI_CONFIGURATION_MODE			UNIDIRECTIONAL_FULL_DUPLEX





#endif /* SPI1_CONFIG_H_ */
